import "./globals.css";
import "normalize.css/normalize.css";

import type { Metadata } from "next";
import { Miriam_Libre } from "next/font/google";
import { ResponsiveLayout } from "@/layouts/responsive-layout";
import { loadFile } from "@/async/loadFile";
import { use } from "react";

const inter = Miriam_Libre({
    weight: ["400", "700"],
    subsets: ["hebrew"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const article: string = use(loadFile());

    return (
        <html lang="en">
            <body className={inter.className}>
                <ResponsiveLayout article={article} />
            </body>
        </html>
    );
}
