import "./globals.css";
import "normalize.css/normalize.css";
import type { Metadata } from "next";
import { Miriam_Libre, Noto_Sans_Hebrew } from "next/font/google";

import YogaButton from "../../public/images/yoga.png";
import CaminoRojoButton from "../../public/images/camino-rojo.jpeg";
import Image from "next/image";
import { DesktopBottomMenu } from "@/components/bottom-menu";
import { PageLink } from "@/components/page-link";
import Link from "next/link";
import { use } from "react";
import { buildArticleMenu, buildMainArticleMenu } from "@/utils/menus";
import { ContentNavigation } from "@/components/content-nav";

const inter = Noto_Sans_Hebrew({
    weight: ["400", "700"],
    subsets: ["hebrew"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const mainArticleLinks = use(buildMainArticleMenu());

    return (
        <html lang="en">
            <body className={inter.className}>
                <nav className="before-scroll">
                    <header>
                        <h1>אש תמיד</h1>
                        <nav className="header-links">
                            {mainArticleLinks
                                .reverse()
                                .map(({ title, href }) => (
                                    <PageLink href={href} text={title} />
                                ))}
                        </nav>
                    </header>

                    <article className="announcements">
                        <marquee truespeed={600}>הודעה לקהל הרחב</marquee>
                    </article>

                    <nav className="navigator">
                        <Link href="/yoga">
                            <div className="navigator-button">
                                <Image
                                    width={100}
                                    height={100}
                                    objectFit="cover"
                                    sizes="100vw"
                                    layout="responsive"
                                    src={YogaButton}
                                    alt="yoga section"
                                />
                                <h2>יוגה</h2>
                            </div>
                        </Link>
                        <Link href="/camino-rojo">
                            <div className="navigator-button">
                                <Image
                                    width={100}
                                    height={100}
                                    objectFit="cover"
                                    sizes="100vw"
                                    layout="responsive"
                                    src={CaminoRojoButton}
                                    alt="Camino Rojo"
                                />
                                <h2>הדרך האדומה</h2>
                            </div>
                        </Link>
                    </nav>
                </nav>

                <main className="under-scroll">
                    <ContentNavigation />
                    <section className="content" id="content">
                        {children}
                    </section>
                </main>
                <footer>
                    <DesktopBottomMenu />
                </footer>
            </body>
        </html>
    );
}
